import https from 'https';

// The URL generated by the server
const url = "https://bcdn.hakunaymatata.com/resource/h265/684b24b1596a134d0b7fad6a74fa3d70.mp4?sign=0f459b03df7729dcb2a8679bd1708991&t=1788298027";

// Let's use a public proxy or service to curl it to see if it fails from a different IP
// We'll use a CORS proxy or similar just to do a remote fetch
https.get(`https://api.allorigins.win/get?url=${encodeURIComponent(url)}`, (res) => {
    let data = '';
    res.on('data', chunk => data+=chunk);
    res.on('end', () => console.log(data.substring(0, 500)));
});
